add spdif on Radxa Zero
radxa/overlays pull request #110
Opened 2023-07-07 08:30 UTC by nascs

根据论坛提供的 patch 整理的，由于没有设备做测试，所以并没有做验证

2023-07-07 08:42 UTC, RadxaYuntian requested changes

2023-07-07 08:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spdif.dts
> +		title = "Enable SPDIF";
```suggestion
		title = "Enable SPDIF on Pin XXX";
```

2023-07-07 08:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spdif.dts
> + 		description = "Enable SPDIF on Radxa Zero";
```suggestion
 		description = "Enable SPDIF on Pin XXX.";
```

2023-07-07 08:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spdif.dts
> +/dts-v1/;
缺少常量定义头文件

2023-07-07 08:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero2-spdif.dts
> + 		compatible = "radxa,zero";
```suggestion
 		compatible = "radxa,zero2";
```

2023-07-07 08:43 UTC, RadxaYuntian commented
@gkkpch

2023-07-07 09:19 UTC, RadxaYuntian reviewed
两个应该可以合并

2023-07-07 09:23 UTC, nascs commented
> 两个应该可以合并

两个文件基本一致，确实可以合并

2023-07-10 06:38 UTC, RadxaYuntian requested changes

2023-07-10 06:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spdif.dts
重命名为`meson-g12-spdif.dts`

2023-07-10 08:06 UTC, RadxaYuntian approved these changes

2023-07-10 08:06 UTC, merged