Add ROCK-5B-gen2's CAM0, CAM1 to support v2 camera overlay.
radxa/overlays pull request #210
Opened 2023-11-10 08:35 UTC by RadxaMitchell

2023-11-10 08:48 UTC, RadxaYuntian requested changes

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-5b-plus-cam0-radxa-camera-v2.dtbo \
1. 名字和内容不符。看看其他raspi cam v2的命名是怎么写的
2. 我感觉其实有一个overlay是应该可以和5b共用的吧？

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam0-radxa-camera-v2.dts
> +            #address-cells = <1>;
```suggestion
			#address-cells = <1>;
```

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam0-radxa-camera-v2.dts
> +				remote-endpoint = <&mipi2_csi2_output>;
```suggestion
					remote-endpoint = <&mipi2_csi2_output>;
```

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam1-radxa-camera-v2.dts
> +            pinctrl-names = "default";
```suggestion
		pinctrl-names = "default";
```

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam1-radxa-camera-v2.dts
> +            #address-cells = <1>;
```suggestion
		#address-cells = <1>;
```

2023-11-10 08:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam1-radxa-camera-v2.dts
> +				remote-endpoint = <&mipi4_csi2_output>;
```suggestion
					remote-endpoint = <&mipi4_csi2_output>;
```

2023-11-10 08:55 UTC, RadxaMitchell commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-5b-plus-cam0-radxa-camera-v2.dtbo \
好像 cam0 的 overlay 是可以和 5b 共用的

2023-11-10 09:00 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-5b-plus-cam0-radxa-camera-v2.dtbo \
可以共用的在共用的overlay那边加上compatible，也可以顺便把上一次的4k cam精简一下

2023-11-13 07:24 UTC, RadxaYuntian requested changes

2023-11-13 07:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam1-rpi-camera-v2.dts
> +#include "rock-5b-rpi-camera-v2.dts"
你这等于完全重写了overlay，还有啥include的必要

2023-11-13 07:27 UTC, RadxaMitchell commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-cam1-rpi-camera-v2.dts
> +#include "rock-5b-rpi-camera-v2.dts"
那 CAM1 就不适用这种方法了，还改回之前 overlay 对吧

2023-11-13 08:18 UTC, RadxaYuntian approved these changes

2023-11-13 08:20 UTC, merged