rk3588: rock 5b: add usbdrd3_dwc3_1 overlay
radxa/overlays pull request #220
Opened 2023-12-01 12:15 UTC by vamrs-feng

2023-12-01 12:20 UTC, RadxaYuntian requested changes

2023-12-01 12:20 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-host.dts
> +		compatible = "radxa,rock-5b";
我记得5b的type a有什么问题不能做otg吧？另外这个支持5b+么？

2023-12-01 12:20 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-host.dts
> +		target = <&usbdrd_dwc3_0>;
```suggestion
		target = <&usbdrd_dwc3_1>;
```

2023-12-01 12:20 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +	fragment@1 {
```suggestion
	fragment@0 {
```
rsetup会保证两个overlay只有一个被加载。在写overlay的时候不要考虑不兼容的overlay被加载的情况

2023-12-01 12:25 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-host.dts
> +		compatible = "radxa,rock-5b";
5B 新版本改到支持了，5b+ 要看看否支持

2023-12-06 03:46 UTC, RadxaYuntian requested changes

2023-12-06 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts
> +			/delete-property/ usb-role-switch;
overlay里面不能使用/delete-property/。要改原始设备树或者怎么重定义一下这个值让相应代码识别为false

2023-12-06 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-host.dts
> +			/delete-property/ usb-role-switch;
overlay里面不能使用/delete-property/。要改原始设备树或者怎么重定义一下这个值让相应代码识别为false

另外你这个在其他产品上测试没有？会不会有额外影响

2023-12-06 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-host.dts
> +		compatible = "radxa,rock-5b";
要说明支持的版本

2023-12-06 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
5B也支持？不是说只有5B+么？

2023-12-06 03:49 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts
> +			/delete-property/ usb-role-switch;
我用了是正常的。

2023-12-06 03:50 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-host.dts
> +			/delete-property/ usb-role-switch;
这个目前 5b 专用

2023-12-06 03:50 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
5B 专用

2023-12-06 03:51 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
Host 模式没有版本限制

2023-12-06 03:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts
> +			/delete-property/ usb-role-switch;
你检查/sys/firmware/devicetree里面是否还有这个属性

2023-12-06 03:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-host.dts
> +			/delete-property/ usb-role-switch;
你的compatible是rk3588，所有rk3588和3588s的设备都会看到这个overlay

2023-12-06 03:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
5B+是怎么设计的

2023-12-06 03:53 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts
> +			/delete-property/ usb-role-switch;
我再看看

2023-12-06 03:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
host overlay最好和这个overlay保持对应，现有用户就知道这个功能跟我没有关系

2023-12-06 03:55 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3_1-peripheral.dts
> +		title = "Set OTG port 1 to Peripheral mode (ROCK 5B V1.46+)";
甚至可以改成`(ROCK 5B V1.46+ Only)`来强调这一点

2023-12-06 09:24 UTC, RadxaYuntian requested changes

2023-12-06 09:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-otg.dts
> +		title = "Set OTG port 0 to otg mode";
```suggestion
		title = "Set OTG port 0 to OTG mode";
```

2023-12-06 09:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-otg.dts
> +		description = "Set OTG port 0 to otg mode.\nUse this for automatic USB role switching.";
```suggestion
		description = "Set OTG port 0 to OTG mode.\nUse this for automatic USB role switching.";
```

2023-12-07 02:32 UTC, RadxaYuntian approved these changes

2023-12-07 02:35 UTC, merged