rock pi s: add poe headphone
radxa/overlays pull request #223
Opened 2023-12-04 08:59 UTC by vamrs-feng

2023-12-04 09:19 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +dtb-$(CONFIG_CPU_RK3308) += \
这个只有使用Rockchip内核时才会定义，但我们现在ROCK Pi S用的是主线内核

2023-12-04 09:57 UTC, RadxaYuntian requested changes

2023-12-04 09:57 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-pi-s-poe-headphone.dts
> +		title = "Enable PoE Hat headphone";
```suggestion
		title = "Enable PoE HAT headphone";
```
要注明具体是哪一款PoE HAT

2023-12-04 09:57 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-pi-s-poe-headphone.dts
> +		description = "Enable PoE Hat headphone.\n";
```suggestion
		description = "Enable PoE HAT headphone.";
```

2023-12-04 09:57 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-pi-s-poe-headphone.dts
> +};
```suggestion
};

```

2023-12-04 09:59 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rock-pi-s-poe-headphone.dts
> +		title = "Enable PoE Hat headphone";
哪个版本是吧

2023-12-04 10:03 UTC, RadxaYuntian approved these changes

2023-12-04 10:04 UTC, RadxaYuntian commented
冲突处理一下

2023-12-05 02:39 UTC, RadxaYuntian approved these changes

2023-12-05 02:41 UTC, merged