enable pin8 & pin10 as gpio
radxa/overlays pull request #224
Opened 2023-12-08 08:09 UTC by nascs

2023-12-08 08:30 UTC, RadxaYuntian requested changes
建议名字改成Disable FIQ Debugger

2023-12-08 08:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-enable-gpio4-c3-c4.dts
> +
应该不需要，uart2本来就没打开

2023-12-08 08:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-enable-gpio4-c3-c4.dts
> +			pinctrl-0 = <&gpio4_c3_c4>;
这里原来是什么值？会不会有影响？

2023-12-08 08:30 UTC, RadxaYuntian commented
同时exclusive需要和fiq_debugger互斥

2023-12-11 09:01 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-enable-gpio4-c3-c4.dts
> +			pinctrl-0 = <&gpio4_c3_c4>;
暂时不会有影响，但是后面如果有其他 overlay 去开启某个 pin 脚的 GPIO 功能的话，可能会有影响

2023-12-11 09:10 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-enable-gpio4-c3-c4.dts
> +			pinctrl-0 = <&gpio4_c3_c4>;
这里原来是什么值？

2023-12-11 09:40 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-enable-gpio4-c3-c4.dts
> +			pinctrl-0 = <&gpio4_c3_c4>;
原来是空的，其他地方没有这样写

2023-12-12 06:09 UTC, RadxaYuntian requested changes
看了下驱动这么写应该问题不大

2023-12-12 06:10 UTC, RadxaYuntian approved these changes

2023-12-12 06:12 UTC, merged