Add debian packaging files
radxa/overlays pull request #238
Opened 2023-12-27 06:37 UTC by CodeChenL

Add debian packaging files

2023-12-27 07:25 UTC, RadxaYuntian requested changes

2023-12-27 07:25 UTC, RadxaYuntian commented on .github/workflows/build.yml
这个里面的功能可以合并到release.yml里面。用户有时候只想要一个现成的dtbo，不想装别的依赖

2023-12-27 07:25 UTC, RadxaYuntian commented on .github/workflows/release.yml
> +          make deb
怎么重复两次？

2023-12-27 07:25 UTC, RadxaYuntian commented on Makefile
> +	gbp dch --debian-branch=main
要仿照rsetup那种，dch能自动生成release commit

2023-12-27 07:25 UTC, RadxaYuntian commented on Makefile
> +
```suggestion
```
额外空行

2023-12-27 07:25 UTC, RadxaYuntian commented on SOURCE
这个文件是Makefile自动生成的，需要添加到.gitignore
Makefile里面可以在deb这里依赖而不是像其他项目一样在build-doc里面依赖

2023-12-27 07:25 UTC, RadxaYuntian commented on Makefile
另外需要make clean支持删除打包的一些中间文件

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/changelog
> +radxa-overlays-dkms (1.0.0-1) UNRELEASED; urgency=medium
```suggestion
radxa-overlays (0.1.0) UNRELEASED; urgency=medium  
```
我们是native包，没有后缀的-X版本号。同时Debian通常是从0.1.0开始计算版本号的。
这里的名字是source package的名字

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/source/format
> +3.0 (quilt)
```suggestion
3.0 (native)
```
参考rsetup

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/compat
> +10
```suggestion
12
```

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/copyright
> +Source: https://github.com/radxa-pkg/overlay
```suggestion
Upstream-Name: overlays
Source: https://github.com/radxa-pkg/overlays
```

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/dkms
> +FORCE=true
```suggestion

```
1. 缺少结尾空格
2. FORCE是个未定义的属性：https://manpages.debian.org/testing/dkms/dkms.8.en.html#DKMS.CONF

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/dkms
> +CLEAN="make clean"
```suggestion
```
CLEAN有默认值，一样的话可以不声明

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/dkms
> +DEST_MODULE_LOCATION[0]="/kernel"
```suggestion
DEST_MODULE_LOCATION[0]="/updates/dkms"
```
Debian好像默认都使用这个路径

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/dkms
> +PACKAGE_NAME="radxa-overlays-dkms"
```suggestion
PACKAGE_NAME="radxa-overlays"
```
这里的名字是source package的名字

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/control
> +Source: radxa-overlays-dkms
```suggestion
Source: radxa-overlays
```
dkms后缀是在生成的包上面添加的，source package不添加
例子：https://packages.debian.org/source/trixie/r8125

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/rules
> +	dh_install -p radxa-overlays-dkms arch usr/src/radxa-overlays-dkms-$(DEB_VERSION)
dh-exec写install试了么？尽量避免修改rules

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/rules
> +
```suggestion
```
dkms包应该不会自动编译，同时lintian我们也配置好了，不需要手动调用

2023-12-27 07:25 UTC, RadxaYuntian commented on debian/source/lintian-overrides
> +radxa-overlays-dkms source: custom-compression-in-debian-rules
```suggestion
radxa-overlays source: custom-compression-in-debian-rules
```

2023-12-27 07:25 UTC, RadxaYuntian commented on radxa-overlays-dkms.ko
这个ko有可能会被用户modprobe，还是弄一个dummy c驱动

2023-12-27 08:15 UTC, CodeChenL commented on debian/rules
> +
是会的

2023-12-27 08:56 UTC, RadxaYuntian commented on debian/rules
> +
你在其他的dkms包运行make deb试试？

2023-12-27 09:00 UTC, CodeChenL commented on debian/rules
> +
其他dkms包的Makefile在src里

2023-12-27 09:00 UTC, CodeChenL commented on debian/rules
> +
> 其他dkms包的Makefile在src文件夹里

2023-12-27 09:36 UTC, CodeChenL commented on debian/dkms
> +CLEAN="make clean"
不一样去掉这行会报错，默认会把install的假ko干掉
![image](https://github.com/radxa/overlays/assets/43897062/f02a570d-b482-4099-af55-eeb48c6264c7)

2023-12-27 09:44 UTC, CodeChenL commented on .github/workflows/build.yml
这个文件不是删了吗

2023-12-27 09:53 UTC, CodeChenL commented on debian/dkms
> +CLEAN="make clean"
> 不一样，去掉这行会报错，默认会把install的假ko干掉 ![image](https://private-user-images.githubusercontent.com/43897062/293004331-f02a570d-b482-4099-af55-eeb48c6264c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzEwNTQsIm5iZiI6MTcwMzY3MDc1NCwicGF0aCI6Ii80Mzg5NzA2Mi8yOTMwMDQzMzEtZjAyYTU3MGQtYjQ4Mi00MDk5LWFmNTUtZWViNDhjNjI2NGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA5NTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTYxNDE4NTg4NDg5NTNhNGQ2ZmQ1ZjA3ZjZhYzE5ZDk2NmE2YTA0NTJiOTRjZWJkZWM2MTFiMDgzODEwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yPrLgvG3c52tiL637lEjjjHp5-OA9AseUn2elVlhPHQ)

看错了，以为你说的`MAKE="make all"`这行

2023-12-27 10:04 UTC, CodeChenL commented on debian/source/lintian-overrides
> +radxa-overlays-dkms source: custom-compression-in-debian-rules
会报错```bash
dpkg-buildpackage: info: binary-only upload (no source included)
 Running lintian-hook
 lintian --fail-on error,warning --suppress-tags bad-distribution-in-changes-file -- radxa-overlays_0.1.0_*.changes
E: radxa-overlays-dkms: alien-tag radxa-overlays: [usr/share/lintian/overrides/radxa-overlays-dkms:2]
debuild: fatal error at line 1184:
lintian --fail-on error,warning --suppress-tags bad-distribution-in-changes-file -- radxa-overlays_0.1.0_*.changes failed
make: *** [Makefile:59：deb] 错误 29
```

2023-12-27 10:10 UTC, RadxaYuntian commented on debian/dkms
> +CLEAN="make clean"
还是要加个dummy module

2023-12-27 10:11 UTC, RadxaYuntian commented on .github/workflows/build.yml
要把里面的功能加回来

2023-12-27 10:19 UTC, RadxaYuntian commented on debian/dkms
> +AUTOINSTALL="yes"
缺少结尾空行

2023-12-27 10:19 UTC, RadxaYuntian commented on debian/install
> +Makefile usr/src/radxa-overlays-${DEB_RADXA_OVERLAYS_VERSION}/
结尾空行

2023-12-27 10:19 UTC, RadxaYuntian commented on debian/source/lintian-overrides
> +radxa-overlays-dkms source: custom-compression-in-debian-rules
解决了吗？

2023-12-27 10:21 UTC, CodeChenL commented on debian/source/lintian-overrides
> +radxa-overlays-dkms source: custom-compression-in-debian-rules
解决不了

2023-12-28 06:43 UTC, RadxaYuntian requested changes

2023-12-28 06:43 UTC, RadxaYuntian commented on radxa-overlays.c
> +MODULE_LICENSE("GPL2");
```suggestion
MODULE_LICENSE("GPL");
```
https://docs.kernel.org/process/license-rules.html

2023-12-28 06:43 UTC, RadxaYuntian commented on radxa-overlays.c
> +MODULE_AUTHOR("© 2022 Radxa Computer Co., Ltd");
```suggestion
MODULE_AUTHOR("Radxa Computer Co., Ltd");
```
作者跟copyright声明是不一样的
另外缺少了结尾空行

2023-12-28 06:43 UTC, RadxaYuntian commented on debian/rules
> +
```suggestion
```
额外空行
文件应以空行结尾，但只有一个

2023-12-28 06:43 UTC, RadxaYuntian commented on debian/dkms
> +CLEAN="make clean cleanmodules"
```suggestion
```
习惯上是make clean就删除所有编译输出，不应该有一个额外的target

2023-12-28 06:43 UTC, RadxaYuntian commented on Makefile
> +	$(MAKE) -C $(KERNEL_HENDERS) M=$(CURDIR) clean
看看别人的makefile怎么写的：https://github.com/furkanmustafa/forcefully-remove-bootfb/blob/master/Makefile

dkms会传入内核头文件地址，不能写死，否则无法支持多个不同的内核版本，或者在我们镜像生成的时候进行安装

2023-12-28 06:43 UTC, RadxaYuntian commented on .gitignore
> +radxa-overlays.ko
```suggestion
*.ko
```
另外缺少结尾空行

2023-12-28 06:43 UTC, RadxaYuntian commented on .github/dependabot.yml
> +      interval: "daily"
缺少结尾空行

2023-12-28 10:54 UTC, CodeChenL commented on debian/dkms
> +CLEAN="make clean cleanmodules"
如果cleanmodules写进clean的话打包时dh_autoclean会报错

2023-12-28 12:06 UTC, RadxaYuntian requested changes

2023-12-28 12:06 UTC, RadxaYuntian commented on .gitignore
> +radxa-overlays.ko
```suggestion
*.ko
```

2023-12-28 12:06 UTC, RadxaYuntian commented on debian/rules
> +	echo "disable dh_auto_build"
```suggestion
```
现在这些应该可以删掉了

2023-12-28 12:06 UTC, RadxaYuntian commented on debian/tmp/dh-exec.V_yjnkis/usr/src/radxa-overlays-0.1.0/Makefile
要gitignore掉

2023-12-28 12:06 UTC, RadxaYuntian commented on radxa-overlays.c
> +MODULE_AUTHOR("2022 Radxa Computer Co., Ltd");
```suggestion
MODULE_AUTHOR("Radxa Computer Co., Ltd");
```

2023-12-28 12:11 UTC, RadxaYuntian commented
Makefile.dkms问题有点多，明天可以一起看一看

https://github.com/aircrack-ng/rtl8812au/blob/v5.6.4.2/Makefile#L1728

2023-12-29 02:07 UTC, RadxaYuntian commented on debian/tmp/dh-exec.V_yjnkis/usr/src/radxa-overlays-0.1.0/Makefile
还是在pr里面

2023-12-29 07:44 UTC, RadxaYuntian requested changes
感觉没啥别的问题了

2023-12-29 07:44 UTC, RadxaYuntian commented on debian/.gitignore
> +/tmp
结尾空行

2023-12-29 07:44 UTC, RadxaYuntian commented on Makefile.dkms
> +TMP				:=	$(addsuffix .tmp,$(DTBO))
```suggestion
DTBO		:=	$(DTBO-AMLOGIC) $(DTBO-ROCKCHIP)
TMP		:=	$(addsuffix .tmp,$(DTBO))
```
对齐缩进

2023-12-29 07:44 UTC, RadxaYuntian commented on Makefile.dkms
> +
```suggestion
```
额外空行

2023-12-29 07:44 UTC, RadxaYuntian commented on Makefile.dkms
> +	$(MAKE) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C $(KSRC) M=$(CURDIR) modules
我觉得还是定义成两个变量，让用户可以override比较好：
https://github.com/lwfinger/rtl8723ds/blob/master/Makefile#L1388-L1389

2023-12-29 10:31 UTC, CodeChenL commented on Makefile.dkms
> +TMP				:=	$(addsuffix .tmp,$(DTBO))
很奇怪，在我本地是对齐的

2023-12-29 10:39 UTC, RadxaYuntian commented on Makefile.dkms
> +TMP				:=	$(addsuffix .tmp,$(DTBO))
你的tab宽度应该是4，github和linux默认是8

2023-12-29 10:43 UTC, RadxaYuntian requested changes
Makefile的tab是有特殊意义的，不能用空格全局替换

2023-12-29 10:48 UTC, RadxaYuntian approved these changes
你把提交历史整理一下吧

2023-12-29 11:05 UTC, CodeChenL commented
好了

2023-12-29 11:23 UTC, RadxaYuntian approved these changes

2023-12-29 11:25 UTC, merged