rockchip: add watch dog support
radxa/overlays pull request #252
Opened 2024-02-06 07:05 UTC by nascs

Signed-off-by: Nascs Fang <nascs@radxa.com>

rk3399, 用的是 4C+ 做的测试， rk356x 用的是 CM3-IO， rk3588 用的是 5B

2024-02-06 07:19 UTC, nascs commented
测试参考的是 https://blog.csdn.net/weixin_43245753/article/details/124269920

2024-02-06 07:32 UTC, RadxaYuntian requested changes
另外看看amlogic的soc有没有watchdog

2024-02-06 07:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-watchdog.dts
> +		title = "Enable Watch Dog";
```suggestion
		title = "Enable Watchdog";
```

2024-02-06 07:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-watchdog.dts
> +		exclusive = "watchdog";
```suggestion
		exclusive = "wdt";
```

2024-02-06 07:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-watchdog.dts
> +		description = "Enable Watch Dog.";
```suggestion
		description = "Enable Watchdog.";
```

2024-02-06 08:30 UTC, RadxaYuntian reviewed
其实你是不是可以创建一个rockchip-watchdog.dts啊，然后把这些soc都放到compatible里面
顺便看看3308和3328有没有wdt

2024-02-06 08:40 UTC, nascs commented
> 其实你是不是可以创建一个rockchip-watchdog.dts啊，然后把这些soc都放到compatible里面 顺便看看3308和3328有没有wdt

确实

2024-02-06 08:51 UTC, nascs commented
> 其实你是不是可以创建一个rockchip-watchdog.dts啊，然后把这些soc都放到compatible里面 顺便看看3308和3328有没有wdt

这样的话，Makefile 也要单独开一个类似于 "dtb-$(CONFIG_CPU_RK3588) += \" 的集合？

2024-02-06 08:54 UTC, RadxaYuntian commented
可以在Makefile里面加一个`dtb-y += rockchip-watchdog.dtbo`

2024-02-06 09:03 UTC, RadxaYuntian requested changes
另外添加amlogic-g12-watchdog.dts

2024-02-06 09:03 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rockchip-watchdog.dts
> +		title = "Enable Watch Dog";
```suggestion
		title = "Enable Watchdog";
```

2024-02-06 09:03 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rockchip-watchdog.dts
> +		compatible = "rockchip,rk3308",  "rockchip,rk3328", "rockchip,rk3399", "rockchip,rk3566", "rockchip,rk3568", "rockchip,rk3588";
```suggestion
		compatible = "rockchip,rk3308", "rockchip,rk3328", "rockchip,rk3399", "rockchip,rk3566", "rockchip,rk3568", "rockchip,rk3588";
```

2024-02-06 10:35 UTC, RadxaYuntian requested changes

2024-02-06 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +dtb-y += amlogic-g12-watchdog.dtbo
这是rockchip的makefile啊，去amlogic那边添加

2024-02-06 10:36 UTC, RadxaYuntian approved these changes
commit合并一下

2024-02-06 10:38 UTC, nascs commented
mainline 的节点是 watchdog， https://github.com/torvalds/linux/blob/99bd3cb0d12e85d5114425353552121ec8f93adc/arch/arm64/boot/dts/amlogic/meson-g12-common.dtsi#L2192C4-L2192C12

2024-02-06 12:12 UTC, RadxaYuntian approved these changes

2024-02-06 12:12 UTC, merged

2024-03-28 07:27 UTC, RadxaYuntian commented
所以为什么overlay在Makefile里面单独加了个dtb-y啊！

2024-03-28 07:36 UTC, nascs commented
> 所以为什么overlay在Makefile里面单独加了个dtb-y啊！

https://github.com/radxa/overlays/pull/252#issuecomment-1929048963

2024-03-28 07:43 UTC, RadxaYuntian commented
当时说的是给rockchip，amlogic本身只有一个target就没必要这么做。我刚刚看到rock 5b的内核现在也包含了amlogic的overlay

回头我看看怎么处理比较好