update overlay for rock5itx
radxa/overlays pull request #253
Opened 2024-02-18 07:56 UTC by Ken-Vamrs

1.close rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp1 overlay
  The hdmiphyclk0 used by dp0 on the software is in conflict with edp0, so disable the dual-display function of edp0 and dp0.

2.add rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp0 overlay

2024-02-19 08:32 UTC, RadxaYuntian requested changes

2024-02-19 08:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-hdmi1-8k.dts
> +		description = "Enable 8K output on HDMI1.\nThis will disable DP0.";
加上exclusive，否则可以同时打开edp和这个overlay，但两个都使用了vp0

2024-02-19 10:05 UTC, RadxaYuntian requested changes

2024-02-19 10:05 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-hdmi1-8k.dts
> +		exclusive = "dp0", "edp0";
```suggestion
		exclusive = "dp0", "vp0", "hdmi1";
```

2024-02-19 10:06 UTC, RadxaYuntian commented
squash一下

2024-02-19 10:27 UTC, Ken-Vamrs commented
> squash一下

ok

2024-02-21 10:06 UTC, RadxaYuntian approved these changes

2024-02-21 10:06 UTC, merged