add rock-5b-allnet-5inch-display overlay
radxa/overlays pull request #256
Opened 2024-02-28 07:02 UTC by Ken-Vamrs

2024-02-28 09:04 UTC, RadxaYuntian requested changes

2024-02-28 09:04 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-allnet-5inch-display.dts
> +		description = "Enable ALLNET 5inch DSI Display";
```suggestion
		description = "Enable ALLNET 5inch DSI Display.";
```

2024-02-28 09:04 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-allnet-5inch-display.dts
> +};
```suggestion
};

```

2024-02-28 09:05 UTC, RadxaYuntian commented
这边的pr不用assign给我

2024-02-29 02:38 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-allnet-5inch-display.dts
> +};
已修改

2024-02-29 03:25 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-allnet-5inch-display.dts
> +};
直接在github pr页面点击re-request for review就行：
![image](https://github.com/radxa/overlays/assets/95260730/9ba9ce0b-8aee-4624-8ee9-ce47031eada7)

2024-02-29 03:26 UTC, RadxaYuntian approved these changes

2024-02-29 03:26 UTC, merged