rock 3b: enable sata2 for hardware <=V1.4 and >1.4
radxa/overlays pull request #262
Opened 2024-03-07 10:55 UTC by nascs

2024-03-07 11:42 UTC, RadxaYuntian requested changes

2024-03-07 11:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3b-sata2.dts
> +		description = "Enable SATA2.\nFor HW <= V.14, it's M.2 M key.\nFor HW <= V.14, it's M.2 E key.\nWhen SATA2 is enabled, PCIe cannot be enabled on the same port.";
看看你写的是什么东西

2024-03-07 11:58 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rock-3b-sata2.dts
> +		description = "Enable SATA2.\nFor HW <= V.14, it's M.2 M key.\nFor HW <= V.14, it's M.2 E key.\nWhen SATA2 is enabled, PCIe cannot be enabled on the same port.";
就是 <= V.14 的 3B，该 overlay 适用于 B key 那个口，硬件版本 > V1.4 的 3B 适用于 E key 那个口

2024-03-07 11:59 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3b-sata2.dts
> +		description = "Enable SATA2.\nFor HW <= V.14, it's M.2 M key.\nFor HW <= V.14, it's M.2 E key.\nWhen SATA2 is enabled, PCIe cannot be enabled on the same port.";
说得好，但这是什么：`HW <= V.14, it's M.2 M key.\nFor HW <= V.14`

2024-03-08 03:32 UTC, RadxaYuntian requested changes
然后squash一下提交

2024-03-08 03:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3b-sata2.dts
> +		description = "Enable SATA2.\nFor HW < 1.5, please insert ssd into B key slot.\nFor HW >= V1.5, please insert ssd into E key slot.\nWhen SATA2 is enabled, PCIe cannot be enabled on the same port.";
```suggestion
		description = "Enable SATA2.\nFor HW < 1.5, the signal is routed to M.2 B key.\nFor HW >= V1.5, the signal is routed to M.2 E key.\nWhen SATA2 is enabled, PCIe cannot be enabled on the same port.";
```

2024-03-08 06:29 UTC, RadxaYuntian approved these changes

2024-03-08 06:29 UTC, RadxaYuntian commented
记得在论坛上提醒客户尝试使用

2024-03-08 06:29 UTC, merged

2024-03-08 06:45 UTC, nascs commented
他想要用的口是 B key 插槽， 但他的是 V1.51。

2024-03-08 06:46 UTC, RadxaYuntian commented
那就实话实说告诉他不行呗