feat: add install overlays feature
radxa/overlays pull request #264
Opened 2024-03-12 07:37 UTC by CodeChenL

* close #257

2024-03-12 07:56 UTC, CodeChenL commented
不知道为什么在dkms执行cp和rm用不了*.dtbo通配符，只能先用find了

2024-03-12 09:33 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
加一个`radxa-overlays.o: $(DTBO)`的依赖关系?

2024-03-12 11:02 UTC, CodeChenL commented on debian/dkms
> +MAKE[0]="make all"
> 加一个`radxa-overlays.o: $(DTBO)`的依赖关系?

没用

2024-03-13 07:14 UTC, RadxaYuntian requested changes

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_build
> +PWD=$(eval pwd)
PWD这个环境变量应该默认就定义了，不需要执行命令。而且就算要执行也不需要用eval，直接`$(pwd)`应该就可以吧？
```suggestion
```

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +if [[ $(readlink "$install_dir/amlogic/overlays") == "$base_dir/amlogic/overlays" ]]
```suggestion
if [[ "$(readlink "$install_dir/amlogic/overlays")" == "$base_dir/amlogic/overlays" ]]
```
任何命令的字符串输出都有包含空格的可能性

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +if [[ $(readlink "$install_dir/rockchip/overlays") == "$base_dir/rockchip/overlays" ]]
```suggestion
if [[ "$(readlink "$install_dir/rockchip/overlays")" == "$base_dir/rockchip/overlays" ]]
```

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +    rm -rf "$install_dir/amlogic/overlays"
```suggestion
    rm "$install_dir/amlogic/overlays"
```
软链接是个文件，直接删除就可以

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +    rm -rf "$install_dir/rockchip/overlays"
```suggestion
    rm "$install_dir/rockchip/overlays"
```

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_install
> +    ln -s "$base_dir/amlogic/overlays" "$install_dir/amlogic/overlays"
如果重复执行会提示软链接已存在，要类似删除一样判断要么对象不存在要么是我们自己创建的软链接
只需要一个if判断就好，`rm -f`对于不存在的文件不会报错

2024-03-13 07:14 UTC, RadxaYuntian commented on debian/dkms.post_install
> +    local install_dir="/usr/lib/linux-image-$kernelver"
安装/卸载内核没有测试么？

2024-03-13 10:16 UTC, RadxaYuntian requested changes

2024-03-13 10:16 UTC, RadxaYuntian commented on debian/dkms.post_install
> +if ! [[ -d "$install_dir/amlogic/overlays" ]] || [[ "$(readlink "$install_dir/amlogic/overlays")" == "$base_dir/amlogic/overlays" ]]
你这个应该是[[ ! -e ]] || [[ readlink ]]可能更好一点，不是d也可能是f或c之类别的东西
另外!放到[[ ]] 里面更明确，避免歧义

2024-03-13 11:23 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
`make -C $kernel_source_dir M=$dkms_tree/$module/$module_version/build`默认的make命令

`always-y += $(DTBO)` 试试：https://docs.kernel.org/kbuild/makefiles.html#always-built-goals-always-y

2024-03-15 10:42 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
$(info $$TMP is [${TMP}])
打印出来TMP是空的

2024-03-15 10:45 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
![image](https://github.com/radxa/overlays/assets/95260730/884e44da-3242-49aa-9823-f70107ca335a)
在dkms里面就是y了

2024-03-15 10:48 UTC, CodeChenL commented on debian/dkms
> +MAKE[0]="make all"
> (info$TMP is [${TMP}]) 打印出来TMP是空的

但是有tmp文件生成啊

2024-03-15 10:50 UTC, CodeChenL commented on debian/dkms.post_install
> +    local install_dir="/usr/lib/linux-image-$kernelver"
测试了，有点不对的是，如果全部内核都卸载了，再安装内核就不生效了。
也就是必须保留一个已经dkms install过的内核。
包括aic8800 dkms也是这种表现

2024-03-15 10:51 UTC, CodeChenL commented on debian/dkms.post_install
> +    local install_dir="/usr/lib/linux-image-$kernelver"
> 测试了，有点不对的是，如果全部内核都卸载了，再安装内核就dkms的自动install不生效了。 也就是必须保留一个已经dkms install过的内核。 包括aic8800 dkms也是这种表现

2024-03-15 11:13 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
kbuild在内核里面定义好了CONFIG_CLK_RK3568=y，导致arch/arm64/boot/dts/rockchip/overlays/Makefile里面dtb-$(CONFIG_CLK_RK3568)=dtb-y而不是dtb-rockchip

2024-03-15 11:19 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
`$(info $(wildcard arch/arm64/boot/dts/*/overlays/Makefile))`打印也是空

2024-03-15 11:20 UTC, RadxaYuntian commented on debian/dkms
> +MAKE[0]="make all"
`$(info $(wildcard *))`则是`Makefile Module.symvers arch include scripts`，是内核头文件里面的内容

2024-03-15 11:24 UTC, CodeChenL commented on debian/dkms
> +MAKE[0]="make all"
我改成这样试试？

2024-03-15 11:24 UTC, CodeChenL commented on debian/dkms
> +MAKE[0]="make all"
![image](https://github.com/radxa/overlays/assets/43897062/2dc7ead1-d0a4-4a9a-b145-ed7773d118ae)

2024-03-18 09:34 UTC, RadxaYuntian requested changes

2024-03-18 09:34 UTC, RadxaYuntian commented on Makefile
> +KSRC := /lib/modules/$(KERNELRELEASE)/build
```suggestion
KSRC ?= /lib/modules/$(KERNELRELEASE)/build
```

2024-03-18 09:34 UTC, RadxaYuntian commented on Makefile
> +clean_dtbo:
```suggestion
clean-dtbo:
```
放到后面clean前面，并注明phony

2024-03-18 09:34 UTC, RadxaYuntian commented on debian/rules
> +	echo "This repository is packaged without compilation"
dkms应该不需要override这个的

2024-03-18 10:02 UTC, CodeChenL commented on debian/rules
> +	echo "This repository is packaged without compilation"
不加override，会执行make,然后顺延到make build

2024-03-18 11:30 UTC, CodeChenL commented on debian/rules
> +	echo "This repository is packaged without compilation"
已修改

2024-03-19 03:44 UTC, RadxaYuntian requested changes

2024-03-19 03:44 UTC, RadxaYuntian commented on Makefile
> +
```suggestion
```
这两好像没有用到？

2024-03-19 03:44 UTC, RadxaYuntian commented on Makefile
> +
```suggestion
```

2024-03-19 08:00 UTC, RadxaYuntian reviewed
自己安装测试一下

```
root@rock-5b:~# dpkg -i /radxa-overlays-dkms_0.1.0_all.deb 
Selecting previously unselected package radxa-overlays-dkms.
(Reading database ... 146543 files and directories currently installed.)
Preparing to unpack .../radxa-overlays-dkms_0.1.0_all.deb ...
Unpacking radxa-overlays-dkms (0.1.0) ...
Setting up radxa-overlays-dkms (0.1.0) ...
Loading new radxa-overlays-0.1.0 DKMS files...
Building for 6.1.43-1-rk2312
Building initial module for 6.1.43-1-rk2312
Done.

radxa-overlays.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.1.43-1-rk2312/updates/dkms/

Running the post_install script:
Link /var/lib/dkms/radxa-overlays/0.1.0/6.1.43-1-rk2312/aarch64/module/arch/arm64/boot/dts/amlogic/overlays to /usr/lib/linux-image-6.1.43-1-rk2312/amlogic/overlays
ln: failed to create symbolic link '/usr/lib/linux-image-6.1.43-1-rk2312/amlogic/overlays': No such file or directory
depmod...
root@rock-5b:~# ls /usr/lib/linux-image-6.1.43-1-rk2312/amlogic/
ls: cannot access '/usr/lib/linux-image-6.1.43-1-rk2312/amlogic/': No such file or directory
root@rock-5b:~# ls /usr/lib/linux-image-6.1.43-1-rk2312/
rockchip
```

2024-03-19 08:01 UTC, RadxaYuntian commented
我觉得可以在没有上层目录的时候跳过

2024-03-19 08:03 UTC, CodeChenL commented
> 我觉得可以在没有上层目录的时候跳过

好，5.10内核有amlogic这个目录所以，我没报错

2024-03-19 09:17 UTC, RadxaYuntian requested changes

2024-03-19 09:17 UTC, RadxaYuntian commented on debian/dkms.post_install
> +fi
这里可以用一个`for vendor in rockchip amlogic`来减少重复代码，然后把这个复杂的判断拆分成几个相对简单的
```
if [[ ! -l "$install_dir/$vendor" ]] || [[ ! -d "$install_dir/$vendor" ]]
then
    # Vendor not supported by the kernel
    continue
elif ...
```
来提高可读性

2024-03-19 09:17 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +if [[ "$(readlink "$install_dir/amlogic/overlays")" == "$base_dir/arm64/boot/dts/amlogic/overlays" ]]
for减少重复代码

2024-03-19 09:17 UTC, RadxaYuntian commented on debian/dkms.post_build
> +cp -a "$PWD/arch" "$base_dir"
先创建目录结构：https://github.com/RadxaOS-SDK/rsdk/blob/main/bin/sub/rsdk-update-product-repo#L49-L51
再用find把所有的dtbo都复制过去吧，现在看了下一大堆乱七八糟的文件

2024-03-19 09:18 UTC, RadxaYuntian commented on debian/dkms.post_install
> +fi
其实这个vendor也可以通过匹配dkms输出boot里面子目录来实现，而不用硬编码

2024-03-19 11:08 UTC, RadxaYuntian requested changes

2024-03-19 11:08 UTC, RadxaYuntian commented on debian/dkms.post_build
> +done
缺少结尾空行

2024-03-19 11:08 UTC, RadxaYuntian commented on debian/dkms.post_build
> +for vendor in "rockchip" "amlogic"
枚举$PWD/arch/arm64/boot/dts/里面的目录来获得vendor

2024-03-19 11:08 UTC, RadxaYuntian commented on debian/dkms.post_install
> +    if [[ -e "$install_dir/$vendor/overlays" ]] && [[ ! -L "$install_dir/$vendor/overlays" ]]
这三个用elif合并一下

2024-03-19 11:41 UTC, RadxaYuntian requested changes

2024-03-19 11:41 UTC, RadxaYuntian commented on debian/dkms.post_build
> +for vendor in $(ls "$PWD/arch/arm64/boot/dts")
你这样如果文件名有空格就会有问题。建议用`"$PWD/arch/arm64/boot/dts"/*`代替，然后在for循环的开始用basename重新给vendor赋值

2024-03-19 11:42 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +base_dir="${PWD%/*}/$(uname -r)/$(arch)/module/arch"
remove应该会有kernelver传入吧？

2024-03-20 01:59 UTC, CodeChenL commented on debian/dkms.post_remove
> +base_dir="${PWD%/*}/$(uname -r)/$(arch)/module/arch"
一开始用的就是变量，发现没有用，才换的uname和arch

2024-03-20 03:59 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +base_dir="${PWD%/*}/$(uname -r)/$(arch)/module/arch"
https://linux.die.net/man/8/dkms:
> Uninstalls an installed module/module-version combo from the kernel/arch passed in the -k option, or the current kernel if the -k option was not passed. upon. **After uninstall completion**, the driver will be left in the built state. To completely remove a driver, **the remove action should be utilized**. 
Remove应该删掉所有内核里面安装的overlay

2024-03-20 06:17 UTC, RadxaYuntian requested changes
https://github.com/radxa/overlays/pull/264#discussion_r1531485421

2024-03-20 07:04 UTC, CodeChenL commented on debian/dkms.post_remove
> +base_dir="${PWD%/*}/$(uname -r)/$(arch)/module/arch"
那会不会出现，卸载一个内核，把另一个还在使用的内核的模块和dtbo删掉的情况？

2024-03-20 07:06 UTC, RadxaYuntian commented on debian/dkms.post_remove
> +base_dir="${PWD%/*}/$(uname -r)/$(arch)/module/arch"
你可以试一试，但卸载内核触发的应该是uninstall而不是remove

2024-03-22 03:08 UTC, CodeChenL commented
post_remove目前的状态能做到删什么内核删对应内核的dtbo了，删除所有内核就删除所有dtbo，应该不需要再改了吧

2024-03-22 03:16 UTC, CodeChenL commented
@RadxaYuntian requested a review

2024-03-28 07:46 UTC, RadxaYuntian requested changes
简单测试了一下好像没问题。整理一下提交吧

2024-03-28 10:49 UTC, merged