rock 2a: add pwm and uart support
radxa/overlays pull request #275
Opened 2024-03-25 03:12 UTC by lsj123lsjlsj

rock 2a: add pwm and uart support

Signed-off-by SongJun Li lisongjun@radxa.com

2024-03-25 03:22 UTC, RadxaYuntian requested changes
缩进有问题。另外麻烦参考一下[这个链接](https://source.android.com/docs/core/architecture/dto/syntax#reference)将overlay的格式修改一下试试看能不能正常使用

2024-03-26 02:00 UTC, lsj123lsjlsj commented
已按照新格式修改并验证

2024-03-26 02:09 UTC, RadxaYuntian requested changes
检查一下你的编辑器缩进设置

2024-03-26 02:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
> +    status = "disabled";
```suggestion
	status = "disabled";
```
tab缩进

2024-03-26 02:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm0-m0.dts
> +    status = "disabled";
缩进

2024-03-26 10:26 UTC, RadxaYuntian approved these changes

2024-03-26 10:27 UTC, merged