rock 2a: add more support and fix problems on some overlays
radxa/overlays pull request #283
Opened 2024-04-02 11:09 UTC by lsj123lsjlsj

rock 2a: add more support and fix problems on some overlays

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-04-02 11:13 UTC, RadxaYuntian requested changes

2024-04-02 11:13 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3528-fiq-debugger-uart7-m0.dtbo \
其他soc格式都是这个为啥你要改？

2024-04-02 11:17 UTC, lsj123lsjlsj commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3528-fiq-debugger-uart7-m0.dtbo \
那是我看错命名格式了

2024-04-02 11:27 UTC, RadxaYuntian requested changes

2024-04-02 11:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3528-fiq-debugger-uart7-m0.dtbo \
makefile也要更新，现在ci就挂了

2024-04-02 11:28 UTC, lsj123lsjlsj commented
刚同步Makefile 合并提交了

2024-04-02 11:37 UTC, RadxaYuntian requested changes

2024-04-02 11:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart2m1.dts
> +		description = "Enable FIQ Debugger on UART2-M1.";
注明引脚

2024-04-02 11:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c0-m1.dts
> +		description = "Enable I2C0-M1.\nOn Radxa 2A IO this is SDA pin 3 and SCL pin 5.";
```suggestion
		description = "Enable I2C0-M1.\nOn Radxa 2A this is SDA pin 3 and SCL pin 5.";
```

2024-04-02 11:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c0-m1.dts
> +		exclusive = "GPIO4_A0", "GPIO4_A1", "i2c2_pinctrl-0";
```suggestion
		exclusive = "GPIO4_A0", "GPIO4_A1", "i2c0";
```

2024-04-02 11:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
> +		exclusive = "GPIO4_A2", "GPIO4_A3", "i2c2_pinctrl-1";
```suggestion
		exclusive = "GPIO4_A2", "GPIO4_A3", "i2c1";
```

2024-04-02 11:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
> +		description = "Enable I2C0-M1.\nOn Radxa 2A IO this is SDA pin 27 and SCL pin 28.";
```suggestion
		description = "Enable I2C1-M0.\nOn Radxa 2A this is SDA pin 27 and SCL pin 28.";
```

2024-04-02 11:48 UTC, lsj123lsjlsj commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
> +		description = "Enable I2C0-M1.\nOn Radxa 2A IO this is SDA pin 27 and SCL pin 28.";
因为2A有1.0和1.1开发板引脚定义需要在所有overlays标注 下次统一将所有overlays修改再提交

2024-04-02 11:49 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
> +		description = "Enable I2C0-M1.\nOn Radxa 2A IO this is SDA pin 27 and SCL pin 28.";
2A都没发布，不需要标注没发售的版本

2024-04-03 02:08 UTC, lsj123lsjlsj commented
合并提交强推了一次 忘了先审核再合并提交

2024-04-03 02:46 UTC, RadxaYuntian requested changes

2024-04-03 02:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
> +		description = "Enable FIQ Debugger on UART1-M0.\nOn Radxa 2A X1.0 this is RX pin 40 and TX pin 36.";
```suggestion
		description = "Enable FIQ Debugger on UART1-M0.\nOn Radxa 2A this is RX pin 40 and TX pin 36.";
```
1. 不要带上内部版本号，我们只标注正式发售的版本
2. 确认这是最新版本的引脚位置，老版本不会发售

2024-04-03 02:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart7m0.dts
> +		description = "Enable FIQ Debugger on UART7-M0.\nOn Radxa 2A X1.0 this is RX pin 27 and TX pin 28.";
```suggestion
		description = "Enable FIQ Debugger on UART7-M0.\nOn Radxa 2A this is RX pin 27 and TX pin 28.";
```

2024-04-03 03:12 UTC, RadxaYuntian requested changes
另外上次review的问题都没处理

2024-04-03 03:12 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart7m0.dts
overlay禁用把compatible设置成unknown：https://github.com/radxa/overlays?tab=readme-ov-file#c-compatible-array

2024-04-03 03:34 UTC, RadxaYuntian requested changes

2024-04-03 03:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
> +		description = "Enable FIQ Debugger on UART1-M0.\nOn Radxa 2A this is RX pin 40 and TX pin 36.";
```suggestion
		description = "Enable FIQ Debugger on UART1-M0.";
```
不兼容就没有对应的引脚

2024-04-03 03:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart7m0.dts
> +		description = "Enable FIQ Debugger on UART7-M0.\nOn Radxa 2A this is RX pin 27 and TX pin 28.";
```suggestion
		description = "Enable FIQ Debugger on UART7-M0.";
```

2024-04-03 03:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-uart1-m0.dts
>  		description = "Enable UART1-M0.\nOn Radxa ROCK 2A this is RX pin 40 & TX pin 36.";
```suggestion
		description = "Enable UART1-M0.";
```

2024-04-03 03:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-uart7-m0.dts
>  		description = "Enable UART7-M0.\nOn Radxa ROCK 2A this is RX pin 27 & TX pin 28.";
```suggestion
		description = "Enable UART7-M0.";
```

2024-04-03 03:45 UTC, RadxaYuntian approved these changes

2024-04-03 03:45 UTC, merged