Rock 5a uart
radxa/overlays pull request #30
Opened 2023-04-11 11:43 UTC by nascs

2023-04-11 12:34 UTC, RadxaYuntian requested changes
uart的overlay都有格式问题

2023-04-11 12:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts
> +		description = "Enable UART2-M0.\nOn Radxa ROCK5A Hardware X1.2 this is TX pin 8 and RX pin 10.";
1. `ROCK5A`中间有空格
2. 除非有硬件不兼容的不要加硬件版本号。跟其他的overlay保持一致

2023-04-11 12:34 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts
>  	fragment@0 {
`uart2-m0`的overlay还需要额外关闭fiqdebugger

2023-04-11 13:04 UTC, RadxaYuntian requested changes

2023-04-11 13:04 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts
> +	fragment@1 {
空行

2023-04-12 06:37 UTC, RadxaYuntian requested changes

2023-04-12 06:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m2-cs0-spidev.dts
> +		exclusive = "";
操作失误？

2023-04-12 06:43 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m2-cs0-spidev.dts
> +		exclusive = "";
可能是，记得这个分支我只改过uart相关的来着

2023-04-12 12:53 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
没有加上uart6m1和8m0

2023-04-13 03:38 UTC, RadxaYuntian requested changes

2023-04-13 03:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1.dts
> +		description = "Enable UART6-M1.\nOn Radxa ROCK 5A Hardware X1.2 this is TX pin 19 and RX pin 21.";
不要带硬件版本号

2023-04-13 06:20 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1.dts
> +		description = "Enable UART6-M1.\nOn Radxa ROCK 5A Hardware X1.2 this is TX pin 19 and RX pin 21.";
检查了一下， 两个版本uart6-m1 所在的pin 不一样，然后其他uart pin 是一样的

2023-04-13 07:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1.dts
> +		description = "Enable UART6-M1.\nOn Radxa ROCK 5A Hardware X1.2 this is TX pin 19 and RX pin 21.";
我们的overlays不需要支持非量产版本，只支持正式版本

2023-04-13 08:07 UTC, RadxaYuntian commented
冲突处理一下

2023-04-18 06:40 UTC, RadxaYuntian commented
没问题就设成Ready for review

2023-04-18 09:01 UTC, RadxaYuntian approved these changes

2023-04-18 09:02 UTC, merged