add uart6 uart8 follow control overlays
radxa/overlays pull request #32
Opened 2023-04-12 09:55 UTC by nascs

2023-04-12 10:43 UTC, RadxaYuntian requested changes

2023-04-12 10:43 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
参照其他overlay命名：`rk3568-uart5-m0-full.dtbo`

2023-04-12 10:43 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-hw-follow-control.dts
> +		title = "Enable UART6-M1 hardware follow control";
参照https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-uart5-m0-full.dts里面的描述

2023-04-12 12:55 UTC, RadxaYuntian requested changes

2023-04-12 12:55 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
>  	rk3588-uart7-m1-ctsn-rtsn.dtbo \
可以把这个文件重命名为`-full`

2023-04-13 07:05 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
>  	rk3588-uart7-m1-ctsn-rtsn.dtbo \
rk3588-uart7-m1-ctsn-rtsn.dtbo, 这个在rock 5a 上是没有的， 到后面rock 5b 的uart pr 来处理

2023-04-18 06:41 UTC, RadxaYuntian requested changes

2023-04-18 06:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
> +		description = "Enable UART6-M1 hardware follow control.\nOn Radxa ROCK 5A this is CTSN pin 24 , RTSN pin 23 , TX pin 19 , and RX pin 21.";
逗号前面不要有空格，逗号后面要有空格

2023-04-18 06:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
> +		description = "Enable UART8-M0 hardware follow control.\nOn Radxa ROCK 5A this is CTSN pin 11, RTSN pin 13 , TX pin 32 , and this is RX pin 40.";
逗号前面不要有空格，逗号后面要有空格

2023-04-18 07:22 UTC, RadxaYuntian commented
没问题的话就设置Ready for review

2023-04-18 07:44 UTC, RadxaYuntian requested changes

2023-04-18 07:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
> +		title = "Enable UART6-M1 hardware follow control";
仿照这里的格式：https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-uart1-m1-full.dts#L6

2023-04-18 07:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
> +		description = "Enable UART6-M1 hardware follow control.\nOn Radxa ROCK 5A this is CTSN pin 24, RTSN pin 23, TX pin 19, and RX pin 21.";
同上更新

2023-04-18 07:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
> +		title = "Enable UART8-M0 hardware follow control";
仿照这里的格式：https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-uart1-m1-full.dts#L6

2023-04-18 07:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
> +		description = "Enable UART8-M0 hardware follow control.\nOn Radxa ROCK 5A this is CTSN pin 11, RTSN pin 13, TX pin 32, and this is RX pin 40.";
同上更新

2023-04-18 07:44 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
> +		description = "Enable UART8-M0 hardware follow control.\nOn Radxa ROCK 5A this is CTSN pin 11, RTSN pin 13, TX pin 32, and this is RX pin 40.";
同时最后不是`, and this is`

2023-04-18 09:02 UTC, RadxaYuntian approved these changes

2023-04-18 09:03 UTC, RadxaYuntian commented
冲突处理一下

2023-04-20 03:01 UTC, merged