add rk3588 one wire example overlay
radxa/overlays pull request #33
Opened 2023-04-12 10:14 UTC by nascs

原打算用GPIO4_B1，后面看了一下，5B上没有这个脚

2023-04-12 11:21 UTC, nascs commented
现在5a 用的pin 40 脚 gpio4_b1

2023-04-12 11:52 UTC, RadxaYuntian requested changes

2023-04-12 11:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3588-w1-gpio4-b2.dtbo \
和文件名不符

2023-04-12 11:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-w1-gpio4-b1.dts
> +		description = "Enable 1-Wire on GPIO4_B1.\nOn Radxa ROCK 5a this is pin 40.";
5<s>a</s>**A**

2023-04-13 03:36 UTC, RadxaYuntian approved these changes

2023-04-13 03:36 UTC, merged