Update compatible for rock 3b
radxa/overlays pull request #46
Opened 2023-04-14 13:22 UTC by Ken-Vamrs

2023-04-17 07:20 UTC, RadxaYuntian requested changes
需要添加对应的exclusive字段

2023-04-20 06:39 UTC, RadxaYuntian reviewed
EM05是和sata复用引脚么？那几个脚还有别的复用的功能么

2023-04-23 06:18 UTC, Ken-Vamrs commented
> EM05是和sata复用引脚么？那几个脚还有别的复用的功能么

3b上是同一个接口，两个功能

2023-04-23 07:27 UTC, RadxaYuntian commented
我的意思是你的exclusive写的是错的，参照https://github.com/radxa/overlays#d-exclusive-array
如果共用的是某个设备树节点（比如dsi_phy1），那就要写那个节点
如果只是单纯的GPIO的复用，那就要写用到的GPIO号

2023-04-23 10:06 UTC, Ken-Vamrs commented
> 我的意思是你的exclusive写的是错的，参照https://github.com/radxa/overlays#d-exclusive-array 如果共用的是某个设备树节点（比如dsi_phy1），那就要写那个节点 如果只是单纯的GPIO的复用，那就要写用到的GPIO号

不冲突使用sata和4G模块，默认去主dts打开

2023-04-23 10:43 UTC, RadxaYuntian commented
这个pr可以改成把这两个overlay删掉

2023-04-23 11:38 UTC, Ken-Vamrs commented
在内核中默认打开，故关闭此pr

2023-04-23 11:38 UTC, closed without merging