add radxa rock 3b pwm compatible support
radxa/overlays pull request #48
Opened 2023-04-17 07:19 UTC by nascs

2023-04-17 07:32 UTC, nascs commented
突然想起 exclusive 字段的作用是防止资源占用，那这样的话, i2c spi  uart pwm这些应该都得加

2023-04-17 07:36 UTC, nascs commented
糟糕的是，我之前只加了GPIO 的 exclusive

2023-04-17 07:38 UTC, RadxaYuntian commented
目前不需要加i2c/spi这些，因为他们是引脚复用的，所以一个用了另外的就不能用了
你把现在overlay里面的pwm先删掉吧

2023-04-17 07:59 UTC, nascs commented
现已删除exclusive里的pwm相关字眼

2023-04-17 08:09 UTC, RadxaYuntian requested changes

2023-04-17 08:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm1-m1.dts
> +		description = "Enable PWM1-M1.\nOn Radxa ROCK 3A hardware V1.2 this pin 28\nOn Radxa ROCK 3A  hardware V1.3/1.31 this is pin 7.\nOn Radxa ROCK 3B this is pin 7.\nOn Radxa E23 this is pin 28.\nOn Ra
On Radxa ROCK 3A <= v1.2 this pin 28\nOn Radxa ROCK 3A >= v1.3 this is pin 7.

2023-04-17 08:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm15-m0.dts
干脆把3c以及下面的fan0节点都删了算了

2023-04-17 08:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm15-m1.dts
干脆把3c以及下面的fan0节点都删了算了

2023-04-18 06:37 UTC, RadxaYuntian requested changes

2023-04-18 06:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm1-m1.dts
> +		description = "Enable PWM1-M1.\nOn Radxa ROCK 3A hardware V1.2 this pin 28\nOn Radxa ROCK 3A  hardware V1.3/1.31 this is pin 7.\nOn Radxa ROCK 3B this is pin 7.\nOn Radxa E23 this is pin 28.\nOn Ra
用上面的文本替换overlay里面的3a描述。

2023-04-18 07:22 UTC, RadxaYuntian approved these changes

2023-04-18 07:23 UTC, merged