Create rk3399-sp2-sc16is752.dts
radxa/overlays pull request #7
Opened 2022-12-27 14:33 UTC by Torndeco

Overlay for https://www.waveshare.com/wiki/2-CH_RS232_HAT using SP2 Someone else might find this useful and update with some param overrides.

Clock defines were annoying hard to get right, due to how linux kernel was probing.
Thankfully found a github issue about it on raspberry pi repos
https://github.com/raspberrypi/linux/issues/3765

SPI2 pins & IRQ = GPIO4_A7
Barely tested using Rock Pi 4b plus. Linux Kernel 5.15-80-rockchip64, but dev/ttySC0  + ttySC1 were created

2022-12-28 03:44 UTC, RadxaYuntian commented
Your latest commit has syntax errors.

2022-12-28 10:11 UTC, Torndeco commented
Should be fixed now, sorry about that

2022-12-28 10:28 UTC, RadxaYuntian requested changes
Please also follow the example in https://github.com/radxa/overlays/commit/9045c4b937e3b8a169f232f5079a67daebc88396 to:
1. Add the overlay in the Makefile (files are ordered alphabetically) 
2. Add `rockchip,pins` definition for the interrupt pin

2022-12-28 10:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-sp2-sc16is752.dts
> +		title = "Enable SC16is752 on SPI2";
`SC16IS752`

2022-12-28 10:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-sp2-sc16is752.dts
> +		description = "Enable SC16is752 SPI on SPI2.\nINT=38";
`SC16IS752`

2022-12-28 10:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-sp2-sc16is752.dts
> +	compatible = "rockchip,rk3399";
This line is not needed in the overlay.

2022-12-28 10:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-sp2-sc16is752.dts
> +			cs-gpios = <&gpio2 RK_PB4 GPIO_ACTIVE_LOW>;
You already defined cs in pinctrl (which uses SPI hardware CS function), so you don't have to redefine it here using GPIO hardware.

2022-12-28 12:25 UTC, Torndeco commented
If i attempt to define the interrupt pins i get error message

rockchip-pinctrl pinctrl: unable to find group for node sc16is752-int-pins
pinctrl-rockchip.c#L338-L342

SImilar error to https://forum.armbian.com/topic/10331-w1_gpio-module-fails-on-asus-tinker-board/

2022-12-28 13:14 UTC, Torndeco commented
Ok have all the changes done except for
2) Add rockchip,pins definition for the interrupt pin  (see previous comment)

2022-12-29 06:59 UTC, RadxaYuntian approved these changes
After checking with the documentation this one doesn't need `rockchip,pins`.

2022-12-29 07:00 UTC, merged