add csi dsi overlays for radxa cm5 io
radxa/overlays pull request #87
Opened 2023-05-26 09:50 UTC by Ken-Vamrs

2023-05-26 10:35 UTC, RadxaYuntian requested changes

2023-05-26 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	radxa-cm5-io-raspi-7inch-touchscreen.dtbo \
需要按照英文字母顺序排列

2023-05-26 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-radxa-display-8hd.dts
> +		title ="Enable Radxa Display 8HD";
既然支持多个DSI那么要在title和description里面说明对应的物理连接：`Enable Radxa Display 8HD on DSI1`

2023-05-26 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-raspi-7inch-touchscreen.dts
> +		title = "Enable Raspberry Pi 7-inch Touchscreen";
物理连接

2023-05-26 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-rpi-camera-v2.dts
> +		exclusive = "csi2_dphy0";
CM5支持多CSI么？支持的话也要注明对应的物理接口

2023-05-30 07:54 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-radxa-display-8hd.dts
> +		title ="Enable Radxa Display 8HD";
当前版本没有dsicsi丝印，下版本会加上，我可以改

2023-05-30 07:54 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	radxa-cm5-io-raspi-7inch-touchscreen.dtbo \
ok

2023-06-15 06:43 UTC, closed without merging